### ISSUE TITLE
main.py error

### ISSUE THREAD

**Issue by leexa90** [tdeboissiere/DeepLearningImplementations#84]
I ran the command and got the following error

python main.py 64 64 

Is there any reason why it throws up an error?

> Traceback (most recent call last):
>   File "main.py", line 73, in <module>
>     launch_training(**d_params)
>   File "main.py", line 8, in launch_training
>     train.train(**kwargs)
>   File "/media/leexa/97ba6a6b-3f4d-4528-84ca-50200ba4594f/Projects/DeepLearningImplementations/pix2pix/src/model/train.py", line 72, in train
>     do_plot)
>   File "/media/leexa/97ba6a6b-3f4d-4528-84ca-50200ba4594f/Projects/DeepLearningImplementations/pix2pix/src/model/models.py", line 310, in load
>     model = generator_unet_upsampling(img_dim, bn_mode, model_name=model_name)
>   File "/media/leexa/97ba6a6b-3f4d-4528-84ca-50200ba4594f/Projects/DeepLearningImplementations/pix2pix/src/model/models.py", line 121, in generator_unet_upsampling
>     list_decoder = [up_conv_block_unet(list_encoder[-1], list_encoder[-2],
> IndexError: list index out of range

**Comment by hayelomt** [comment]
You can run it with tensorflow backend, it'll fix the issue
python main.py 64 64 --backend tensorflow
